server:
  port: 8761


#Eureka配置
eureka:
  instance:
    hostname: localhost #Eureka服务端的实例名称
  client:
    service-url: #监控页面
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false #表示是否将自己注册到Eureka Server，默认为true - 固定配置
    fetch-registry: false  #表示是否从Eureka Server获取注册信息，默认为true ; 如果为false,则表示自己为注册中心 - 固定配置

#数据库连接
spring:
  application:
    name: eurekaservice
  datasource:
    url: jdbc:mysql://106.14.5.63:3306/fsd2020?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMutiQueries=true
    username: mysql
    password: 594Caoyizheng!
    driver-class-name: com.mysql.cj.jdbc.Driver